name: fmt

on:
  push:
    branches:
      - dev
  repository_dispatch:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-20.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: fmt
      run: |
        sudo apt update && sudo apt install minify
        echo "$(minify dev/style.css)" > htdocs/luci-static/design/css/style.css
        echo "$(minify dev/script.js)" > htdocs/luci-static/design/js/script.js
        echo "$(minify dev/xhr.js)" > htdocs/luci-static/design/js/xhr.js
        echo "$(minify dev/design.js)" > htdocs/luci-static/design/js/design.js
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        base: dev
        token: ${{ secrets.TOKEN }}
        branch: fmt
        delete-branch: true
        add-paths: |
          htdocs/luci-static/design/css/style.css
          htdocs/luci-static/design/js/script.js
          htdocs/luci-static/design/js/xhr.js
          htdocs/luci-static/design/js/design.js
        title: "style: format and compress js and css resources"
        commit-message: "style: format and compress js and css resources"